name: Release
on:
  push:
    tags:
      - 'v*'
jobs:
  build-idea-plugin:
    name: Build IdeaLSP plugin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get the version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT


      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
      - name: Build plugins
        uses: gradle/gradle-build-action@v3
        env:
          IDEALSP_VERSION: ${{ steps.get_version.outputs.VERSION }}
        with:
          arguments: :buildPlugin
          build-root-directory: server
      - name: Upload plugin artifact
        uses: actions/upload-artifact@v4
        with:
          name: idealsp-plugin-${{ steps.get_version.outputs.VERSION }}
          path: "server/build/distributions/*.zip"